---

- stat: path={{ steamcmd_directory }}steamcmd.sh
  register: steamcmd

- name: check if steamcmd exists
  fail:
    msg: unable to find {{ steamcmd_directory }}steamcmd.sh, you may uses lutangar/ansible-role-steamcmd to set it up
  when: not steamcmd.stat.exists

- name: Check if is the server token is set.
  fail:
    msg: you must set the dst_server_token, you can generate one by entering `TheNet:GenerateServerToken()` in the Don't Starve Toghether console
  when: not dst_server_token
